jesserizzo/envoy_reader

README.md
envoy_reader/__init__.py
envoy_reader/envoy_reader.py

older Envoys (mine....) with software before R3.9, do not have the .json data available, only .html pages, http://envoy/production is the main one.    added code to detect this older version of Envoy and scrape the html.
my envoy_reader.py doesn't use the recently added await commands, I couldn't get requests_async working.  But otherwise it works on my system now, and I believe it shouldn't break any of the .json based data collection for newer Envoys.
also updated the README.md file
please let me know if anything else I should do or fix,   Thanks,   Dale

support older Envoy C with only .html, no .json

---

envoy_reader/envoy_reader.py

This small tweak fixes the check of the json length , which was causing a false negative on the detection of my Envoy-S with consumption metering. My Envoy-S returns two top sections, one for production and one for consumption.
```
$ curl -s http://envoy/production.json | jq length
2
```
This manifested as envoy_reader failing to pull my consumption data ("Consumption data not available for your Envoy device.") and was less transparent as it was reported in Home Assistant ("Unable to connect to Envoy. Check that the device is up at 'http://envoy'.").
I left it as a >=2 check since I'm unsure if other Envoy-S hardware revisions have different output. Has someone else confirmed they have a json response with 3 sections?

Improve detection of Envoy-S with consumption metering

---

envoy_reader/envoy_reader.py

Due to the asynchronous nature of this code, whenever a consumption call is made, and the model is not yet known from a 'production' call, the `message_consumption_not_available` is not returned, because the model is still an empty string.
This is in the case where the Envoy model does not support 'consumption'.
This merge request should fix these cases by also doing a model detection on the consumption calls.
I'll link an issue I am drafting from another project that is using this library as a plugin with a more detailed report.
Let me know what you think :)

Fix support for Envoy 'P' models that do not have consumption capabilities

---

envoy_reader/envoy_reader.py

The Envoy API was printing out a message to the console when inverter data was unable to be collected.  For Home Assistant to consume and log the error in its own log, I raised an exception instead.
There are other cases where the error messages being printed to the console will not be displayed in the HA logs.  But given my lack of knowledge with exceptions, I didn't want to change too much code! :grin:
This change is for the HA PR [#28837](https://github.com/home-assistant/home-assistant/pull/28837)

Raise an exception when Authentication fails for Inverter data

---

envoy_reader/envoy_reader.py

This PR should improve the model detection of different types.
Currently the type I test with is a P-type, which has the following production.json:
```
{
"production" : [
{
"activeCount" : 12,
"readingTime" : 12345678,
"type" : "inverters",
"whLifetime" : 12345678,
"wNow" : 123
}
],
"storage" : [
{
"activeCount" : 0,
"type" : "acb",
"readingTime" : 0,
"state" : "idle",
"whNow" : 0,
"wNow" : 0
}
]
}
```
The device I am testing with is not my own, and thus I don't always have access to it.
I am trying to fix homeassistant integration with this, and after using this patch and the previous PR, the values show up in HA.
Would be nice if somebody with a PC-type could test that this patch doesn't break anything.

Use better detection for PC type

---

envoy_reader/envoy_reader.py

Add in a single method that Home Assistant will use to grab data once every time it polls.
This is not a complete fix, but a beginning to reduce the number of calls being made to Envoys.  Using this method and an updated HA sensor code the Envoy running firmware >= 3.9 is not overwhelmed which previously caused the Envoy to not respond sometimes when requesting inverter data.

Add a single entry point for Home Assistant

---

envoy_reader/envoy_reader.py
requirements.txt

Home Assistant 0.109 is now checking if I/O is occurring within the event loop and then logging a Warning message.  This message is occurring with the envoy sensor due to the [requests_sync call](https://github.com/jesserizzo/envoy_reader/blob/ee176190ebe95d98d6414deecf6d710438270cf9/envoy_reader/envoy_reader.py#L359) that is called from an async HA call
I was unable to get the currently used `requests_async` library or the preferred HTTP library of `aiohttp` to work with HTTP Digest Authentication.  So I changed the `inverters_production()` method to use the `httpx` library
Fixes #28

Replace sync inverter call with async

---

setup.py

`Setup.py` has to be updated so that `httpx` library gets installed, when the `envoy_reader` module is installed
Fix #30

Update setup.py to include new httpx required library

---

envoy_reader/envoy_reader.py

Increased timeout from default of 5secs to 30secs
Fixes #34

Increase HTTP timeout for inverter production call

---

envoy_reader/envoy_reader.py

Issue #37 mentioned that data is not correct when Metering on an Envoy S/IQ Envoy is not enabled.
Looking at the code the ["production"][1]["wNow"] is retrieved from the /production.json page. This section of the json page is used for the Production value for a CT that is installed to read the production from the solar array.  In some cases the Envoy uses ["production"][1]["wNow"] AND ["production"][0]["wNow"] when metering is not enabled.  Not sure if this is in the Envoy firmware or if the user has CTs installed and the firmware reads the sensor but has not enabled/setup metering.
In any case to fix the problem that Issue #37 has the code has changed to look at the ["production"][1]["activeCount"] value. If the value is 0 than this says Metering is not enabled on the Envoy and the …

Retrieve Production data based on CT (eim) count

---

envoy_reader/envoy_reader.py
setup.py

In previous versions of `envoy_reader` a message was being returned when an error occurred. Here I changed to the returned of a failure to an exception so that Home Assistant can consume and handle the exception rather than parsing a string

Raise exceptions that Home Assistant can consume

---

envoy_reader/envoy_reader.py
setup.py

Removed references to `requests_async` library and replaced HTTP requests with the `httpx` library
Fixes #48

Replace requests_async with httpx library

---

envoy_reader/envoy_reader.py
setup.py

During testing it was found that a bug was introduced in 0.17.0 that broke getting Production data for Envoys running <3.9 firmware.
This PR backports the fix from 0.17.2 release, and also includes a change in 0.17.2 that does not gather Inverter data for Envoys running <3.9 as they do not support this.

Create hotfix to fix Production data issue with <3.9 firmware

---

setup.py

I guess the letter at the end of the version string indicates a Pre-Release, so as to avoid confusion the hotfix will be bumped to 0.17.3. And in another PR the `master` with the latest changes (since the hotfix was selective backports and some changes did occur from 0.17.1 to 10.17.2 which are currently not needed) will be bumped to 0.18.0

Change version number for hotfix

---

envoy_reader/envoy_reader.py

Making this change as Home Assistant does not want I/O to occur when updating entities.
This change makes it so where the getData() method will retrieve the data, and the other methods will only retrieve what is stored in variables.
Changes that I made at a high-level:
- HTTP requests to Envoys with firmware <3.9 was moved to `getData()`. Other firmwares the HTTP requests (except for Inverter data gathering) was already moved to `getData()`
- Move Inverter gathering to `getData()`
- To support gathering Inverter data I added an optional parameter for the EnvoyReader constructor. So that if Home Assistant config does not have `inverters` then this can be skipped.
- Removed `detect_model()` methods from individual methods and runs only from `getData()`
- Removed `isDataRetrieved` boolean, …

Let I/O occur only when calling getData()

---

envoy_reader/envoy_reader.py
setup.py

It seems after moving from [requests-async](https://github.com/encode/requests-async) to the [httpx](https://www.python-httpx.org/) library, gathering inverter data sometimes fails.
The [httpx documentation](https://www.python-httpx.org/exceptions/) says `The protocol was violated by the server.` While I've seen a [reference](https://github.com/home-assistant/core/issues/43384) to this occurring when the endpoint is overwelmed.  In my case, I don't think it is the latter, as I was not seeing this issue when using the `requests-async` library.
In any case, I have added a retry mechanism when getting inverter data. If after 3 retries we still get the same `httpx.RemoteProtocolError`, than the library will raise the exception. When using the library in Home Assistant the retry will hopefully …

Add retries when gathering Inverter data

---

envoy_reader/envoy_reader.py
setup.py

Fix #60 
Returning `None` rather than a string when retrieving inverter data for an Envoy that does not support inverter data (<3.9 firmware)

Return None for Inverter data for Envoy with <3.9 firmware

---

.github/workflows/build-main.yml

Given the low number of changes to the repository I feel we can get away with running Workflows with PR merges and commits to main
**Pull request recommendations:**
Thanks for contributing!

Remove schedule from build-main workflow

---

envoy_reader/envoy_reader.py

_feature/optional-fetch-inverters_
Update getData() to add optional input parameter to not read inverters.
Inverters only update every 5 or 15 mins, depending on Envoy-S configuration, whereas production data updates every minute.  Also, requesting inverter data at too short an interval can cause the Envoy to start lagging and eventually timeout.  See [https://thecomputerperson.wordpress.com/2016/08/03/enphase-envoy-s-data-scraping/#comment-1565](https://thecomputerperson.wordpress.com/2016/08/03/enphase-envoy-s-data-scraping/#comment-1565) for more details.

Update envoy_reader.py getData()

---

envoy_reader/envoy_reader.py
setup.py

Adding Battery storage data that is coming from ```/production.json```
```
"storage": [{"type": "acb","activeCount": 4,"readingTime": 1595203104,"wNow": -178,"whNow": 285,"state": "charging","percentFull": 6}
```
Battery storage data will only be returned when the battery is installed in the Envoy system. To determine if the battery is installed we check for the presence of the ```percentFull``` attribute, as in the above example.
If a battery is not present the ```/production.json``` page will return:
```
"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}
```
In which case the API will return a message saying the battery storage is not available.
**Pull request recommendations:**
Thanks for contributing!

Add Battery storage data

---

envoy_reader/envoy_reader.py
setup.py

**Pull request recommendations:**
The `EnvoyUtils.get_password()` will generate a password for the `installer` account. Does not create a password for other accounts, but I have left it in the code that the `get_password()` will be run if the account is `!= envoy` just in case there are other accounts that this will work for.
Thanks for contributing!

Use library to generate and consume password

---

envoy_reader/envoy_reader.py
setup.py

WIth [`httpx-0.20.0`](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0200-13th-october-2021) the signature changed.
A lot of distributions and Home Assistant will support `httpx-0.20.0`.

Support for later httpx releases

---

requirements.txt
setup.cfg
setup.py

Bumping API to version 0.20.1
Changes are:
- use httpx >= 0.20
- define the MIT license in setup.py

Bump API version to 0.20.1
